language: ruby
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - jruby-9.0.5.0
  - 2.1.10
  - 2.0.0-p648
gemfile:
  - gemfiles/rails5_2.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_0.gemfile
matrix:
  exclude:
    - rvm: 2.0.0-p648
      gemfile: gemfiles/rails5_2.gemfile
    - rvm: 2.0.0-p648
      gemfile: gemfiles/rails5_1.gemfile
    - rvm: 2.0.0-p648
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_0.gemfile
